'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
exports.SoftwareProvider = exports.AuthorizationProvider = exports.InvoiceSource = exports.AuthorizedInvoices = exports.InvoiceControl = exports.DianExtensionsContent = exports.DianExtensions = exports.UBLExtensionType = exports.UBLExtensions = void 0;
const UBLExtensionsType_1 = require("./UBLExtensionsType");
Object.defineProperty(exports, "UBLExtensions", { enumerable: true, get: function () { return UBLExtensionsType_1.UBLExtensions; } });
const UBLExtension_1 = require("./UBLExtension");
Object.defineProperty(exports, "UBLExtensionType", { enumerable: true, get: function () { return UBLExtension_1.UBLExtensionType; } });
const customExtensionContents_1 = require("./customExtensionContents");
Object.defineProperty(exports, "DianExtensions", { enumerable: true, get: function () { return customExtensionContents_1.DianExtensions; } });
Object.defineProperty(exports, "DianExtensionsContent", { enumerable: true, get: function () { return customExtensionContents_1.DianExtensionsContent; } });
Object.defineProperty(exports, "AuthorizationProvider", { enumerable: true, get: function () { return customExtensionContents_1.AuthorizationProvider; } });
Object.defineProperty(exports, "InvoiceControl", { enumerable: true, get: function () { return customExtensionContents_1.InvoiceControl; } });
Object.defineProperty(exports, "AuthorizedInvoices", { enumerable: true, get: function () { return customExtensionContents_1.AuthorizedInvoices; } });
Object.defineProperty(exports, "InvoiceSource", { enumerable: true, get: function () { return customExtensionContents_1.InvoiceSource; } });
Object.defineProperty(exports, "SoftwareProvider", { enumerable: true, get: function () { return customExtensionContents_1.SoftwareProvider; } });
