"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UdtTypes = exports.Address = exports.AddressLine = exports.CctBinaryObjectType = exports.CctAmountType = exports.Invoice = void 0;
const cct_1 = require("./ubl21/types/UnqualifiedDataTypes/essentials/cct");
Object.defineProperty(exports, "CctAmountType", { enumerable: true, get: function () { return cct_1.CctAmountType; } });
Object.defineProperty(exports, "CctBinaryObjectType", { enumerable: true, get: function () { return cct_1.CctBinaryObjectType; } });
const AddressLine_1 = require("./ubl21/CommonAggregateComponents/AddressLine");
Object.defineProperty(exports, "AddressLine", { enumerable: true, get: function () { return AddressLine_1.AddressLine; } });
const AddressTypeGroup_1 = require("./ubl21/CommonAggregateComponents/AddressTypeGroup");
Object.defineProperty(exports, "Address", { enumerable: true, get: function () { return AddressTypeGroup_1.Address; } });
const UdtTypes = require("./ubl21/types/UnqualifiedDataTypes");
exports.UdtTypes = UdtTypes;
const schemaDocuments_1 = require("./ubl21/schemaDocuments");
Object.defineProperty(exports, "Invoice", { enumerable: true, get: function () { return schemaDocuments_1.Invoice; } });
