"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Contact = exports.PostalAddress = exports.CorporateRegistrationScheme = exports.PartyLegalEntity = exports.TaxRepresentativeParty = exports.PartyTaxScheme = exports.TaxScheme = exports.DespatchAddress = exports.DeliveryAddress = exports.JurisdictionRegionAddress = exports.RegistrationAddress = exports.AddressParams = exports.Address = exports.DespatchLocation = exports.AlternativeDeliveryLocation = exports.DeliveryLocation = exports.PhysicalLocation = exports.Country = exports.AddressLine = exports.DespatchParty = exports.NotifyParty = exports.DeliveryParty = exports.IssuerParty = exports.CarrierParty = exports.Party = exports.AccountingSupplierParty = exports.Signature = exports.ProjectReference = exports.AdditionalDocumentReference = exports.ContractDocumentReference = exports.OriginatorDocumentReference = exports.StatementDocumentReference = exports.ReceiptDocumentReference = exports.DespatchDocumentReference = exports.InvoiceDocumentReference = exports.BillingReference = exports.Language = exports.PartyName = exports.PartyIdentification = exports.PriceList = exports.RequestedDespatchPeriod = exports.EstimatedDespatchPeriod = exports.InvoicePeriodBasic = exports.EstimatedDeliveryPeriod = exports.PromisedDeliveryPeriod = exports.RequestedDeliveryPeriod = exports.ValidityPeriod = exports.PeriodType = exports.DocumentReference = exports.OrderReference = void 0;
exports.CommodityClassification = exports.DebitNoteLine = exports.SubCreditNoteLine = exports.CreditNoteLine = exports.InvoiceLine = exports.ItemPriceExtension = exports.Price = exports.AllowanceCharge = exports.SupplyItem = exports.Item = exports.RequestLineReference = exports.ReceiptLineReference = exports.QuotationLineReference = exports.ParentDocumentLineReference = exports.DependentLineReference = exports.CatalogueLineReference = exports.CallForTendersLineReference = exports.DespatchLineReference = exports.LineReference = exports.OrderLineReference = exports.LegalMonetaryTotal = exports.MonetaryTotal = exports.TaxSubtotal = exports.ClassifiedTaxCategory = exports.TaxCategory = exports.WithholdingTaxTotal = exports.TaxTotal = exports.PricingExchangeRate = exports.PaymentExchangeRate = exports.ExchangeRate = exports.PrepaidPayment = exports.PaymentType = exports.PaymentTerms = exports.PaymentMeans = exports.DeliveryTerms = exports.Delivery = exports.ShipmentType = exports.MinimumDeliveryUnit = exports.MaximumDeliveryUnit = exports.DeliveryUnit = exports.Despatch = exports.AccountingCustomerParty = exports.BuyerContact = exports.AccountingContact = exports.DeliveryContact = void 0;
const OrderReference_1 = require("./OrderReference");
Object.defineProperty(exports, "OrderReference", { enumerable: true, get: function () { return OrderReference_1.OrderReference; } });
const PeriodTypeGroup_1 = require("./PeriodTypeGroup");
Object.defineProperty(exports, "PeriodType", { enumerable: true, get: function () { return PeriodTypeGroup_1.PeriodType; } });
Object.defineProperty(exports, "InvoicePeriodBasic", { enumerable: true, get: function () { return PeriodTypeGroup_1.InvoicePeriodBasic; } });
Object.defineProperty(exports, "RequestedDeliveryPeriod", { enumerable: true, get: function () { return PeriodTypeGroup_1.RequestedDeliveryPeriod; } });
Object.defineProperty(exports, "EstimatedDeliveryPeriod", { enumerable: true, get: function () { return PeriodTypeGroup_1.EstimatedDeliveryPeriod; } });
Object.defineProperty(exports, "EstimatedDespatchPeriod", { enumerable: true, get: function () { return PeriodTypeGroup_1.EstimatedDespatchPeriod; } });
Object.defineProperty(exports, "RequestedDespatchPeriod", { enumerable: true, get: function () { return PeriodTypeGroup_1.RequestedDespatchPeriod; } });
Object.defineProperty(exports, "PromisedDeliveryPeriod", { enumerable: true, get: function () { return PeriodTypeGroup_1.PromisedDeliveryPeriod; } });
Object.defineProperty(exports, "ValidityPeriod", { enumerable: true, get: function () { return PeriodTypeGroup_1.ValidityPeriod; } });
const PartyIdentification_1 = require("./PartyIdentification");
Object.defineProperty(exports, "PartyIdentification", { enumerable: true, get: function () { return PartyIdentification_1.PartyIdentification; } });
const PartyName_1 = require("./PartyName");
Object.defineProperty(exports, "PartyName", { enumerable: true, get: function () { return PartyName_1.PartyName; } });
const Language_1 = require("./Language");
Object.defineProperty(exports, "Language", { enumerable: true, get: function () { return Language_1.Language; } });
const BillingReference_1 = require("./BillingReference");
Object.defineProperty(exports, "BillingReference", { enumerable: true, get: function () { return BillingReference_1.BillingReference; } });
const DocumentReferenceGroup_1 = require("./DocumentReferenceGroup");
Object.defineProperty(exports, "DespatchDocumentReference", { enumerable: true, get: function () { return DocumentReferenceGroup_1.DespatchDocumentReference; } });
Object.defineProperty(exports, "DocumentReference", { enumerable: true, get: function () { return DocumentReferenceGroup_1.DocumentReference; } });
Object.defineProperty(exports, "InvoiceDocumentReference", { enumerable: true, get: function () { return DocumentReferenceGroup_1.InvoiceDocumentReference; } });
Object.defineProperty(exports, "ReceiptDocumentReference", { enumerable: true, get: function () { return DocumentReferenceGroup_1.ReceiptDocumentReference; } });
Object.defineProperty(exports, "StatementDocumentReference", { enumerable: true, get: function () { return DocumentReferenceGroup_1.StatementDocumentReference; } });
Object.defineProperty(exports, "OriginatorDocumentReference", { enumerable: true, get: function () { return DocumentReferenceGroup_1.OriginatorDocumentReference; } });
Object.defineProperty(exports, "ContractDocumentReference", { enumerable: true, get: function () { return DocumentReferenceGroup_1.ContractDocumentReference; } });
Object.defineProperty(exports, "AdditionalDocumentReference", { enumerable: true, get: function () { return DocumentReferenceGroup_1.AdditionalDocumentReference; } });
const ProjectReference_1 = require("./ProjectReference");
Object.defineProperty(exports, "ProjectReference", { enumerable: true, get: function () { return ProjectReference_1.ProjectReference; } });
const Signature_1 = require("./Signature");
Object.defineProperty(exports, "Signature", { enumerable: true, get: function () { return Signature_1.Signature; } });
const SupplierPartyTypeGroup_1 = require("./SupplierPartyTypeGroup");
Object.defineProperty(exports, "AccountingSupplierParty", { enumerable: true, get: function () { return SupplierPartyTypeGroup_1.AccountingSupplierParty; } });
const PartyTypeGroup_1 = require("./PartyTypeGroup");
Object.defineProperty(exports, "Party", { enumerable: true, get: function () { return PartyTypeGroup_1.Party; } });
Object.defineProperty(exports, "TaxRepresentativeParty", { enumerable: true, get: function () { return PartyTypeGroup_1.TaxRepresentativeParty; } });
Object.defineProperty(exports, "CarrierParty", { enumerable: true, get: function () { return PartyTypeGroup_1.CarrierParty; } });
Object.defineProperty(exports, "IssuerParty", { enumerable: true, get: function () { return PartyTypeGroup_1.IssuerParty; } });
Object.defineProperty(exports, "DeliveryParty", { enumerable: true, get: function () { return PartyTypeGroup_1.DeliveryParty; } });
Object.defineProperty(exports, "NotifyParty", { enumerable: true, get: function () { return PartyTypeGroup_1.NotifyParty; } });
Object.defineProperty(exports, "DespatchParty", { enumerable: true, get: function () { return PartyTypeGroup_1.DespatchParty; } });
const AddressLine_1 = require("./AddressLine");
Object.defineProperty(exports, "AddressLine", { enumerable: true, get: function () { return AddressLine_1.AddressLine; } });
const CountryTypeGroup_1 = require("./CountryTypeGroup");
Object.defineProperty(exports, "Country", { enumerable: true, get: function () { return CountryTypeGroup_1.Country; } });
const CommodityClassificationTypeGroup_1 = require("./CommodityClassificationTypeGroup");
Object.defineProperty(exports, "CommodityClassification", { enumerable: true, get: function () { return CommodityClassificationTypeGroup_1.CommodityClassification; } });
const LocationTypeGroup_1 = require("./LocationTypeGroup");
Object.defineProperty(exports, "PhysicalLocation", { enumerable: true, get: function () { return LocationTypeGroup_1.PhysicalLocation; } });
Object.defineProperty(exports, "DeliveryLocation", { enumerable: true, get: function () { return LocationTypeGroup_1.DeliveryLocation; } });
Object.defineProperty(exports, "AlternativeDeliveryLocation", { enumerable: true, get: function () { return LocationTypeGroup_1.AlternativeDeliveryLocation; } });
Object.defineProperty(exports, "DespatchLocation", { enumerable: true, get: function () { return LocationTypeGroup_1.DespatchLocation; } });
const AddressTypeGroup_1 = require("./AddressTypeGroup");
Object.defineProperty(exports, "Address", { enumerable: true, get: function () { return AddressTypeGroup_1.Address; } });
Object.defineProperty(exports, "AddressParams", { enumerable: true, get: function () { return AddressTypeGroup_1.AddressParams; } });
Object.defineProperty(exports, "RegistrationAddress", { enumerable: true, get: function () { return AddressTypeGroup_1.RegistrationAddress; } });
Object.defineProperty(exports, "JurisdictionRegionAddress", { enumerable: true, get: function () { return AddressTypeGroup_1.JurisdictionRegionAddress; } });
Object.defineProperty(exports, "DeliveryAddress", { enumerable: true, get: function () { return AddressTypeGroup_1.DeliveryAddress; } });
Object.defineProperty(exports, "DespatchAddress", { enumerable: true, get: function () { return AddressTypeGroup_1.DespatchAddress; } });
const TaxScheme_1 = require("./TaxScheme");
Object.defineProperty(exports, "TaxScheme", { enumerable: true, get: function () { return TaxScheme_1.TaxScheme; } });
const PartyTaxScheme_1 = require("./PartyTaxScheme");
Object.defineProperty(exports, "PartyTaxScheme", { enumerable: true, get: function () { return PartyTaxScheme_1.PartyTaxScheme; } });
const PartyLegalEntity_1 = require("./PartyLegalEntity");
Object.defineProperty(exports, "PartyLegalEntity", { enumerable: true, get: function () { return PartyLegalEntity_1.PartyLegalEntity; } });
const CorporateRegistrationScheme_1 = require("./CorporateRegistrationScheme");
Object.defineProperty(exports, "CorporateRegistrationScheme", { enumerable: true, get: function () { return CorporateRegistrationScheme_1.CorporateRegistrationScheme; } });
const ContactTypeGroup_1 = require("./ContactTypeGroup");
Object.defineProperty(exports, "Contact", { enumerable: true, get: function () { return ContactTypeGroup_1.Contact; } });
Object.defineProperty(exports, "DeliveryContact", { enumerable: true, get: function () { return ContactTypeGroup_1.DeliveryContact; } });
Object.defineProperty(exports, "AccountingContact", { enumerable: true, get: function () { return ContactTypeGroup_1.AccountingContact; } });
Object.defineProperty(exports, "BuyerContact", { enumerable: true, get: function () { return ContactTypeGroup_1.BuyerContact; } });
const PostalAddressTypeGroup_1 = require("./PostalAddressTypeGroup");
Object.defineProperty(exports, "PostalAddress", { enumerable: true, get: function () { return PostalAddressTypeGroup_1.PostalAddress; } });
const CustomerPartyTypeGroup_1 = require("./CustomerPartyTypeGroup");
Object.defineProperty(exports, "AccountingCustomerParty", { enumerable: true, get: function () { return CustomerPartyTypeGroup_1.AccountingCustomerParty; } });
const Despatch_1 = require("./Despatch");
Object.defineProperty(exports, "Despatch", { enumerable: true, get: function () { return Despatch_1.Despatch; } });
const DeliveryUnitTypeGroup_1 = require("./DeliveryUnitTypeGroup");
Object.defineProperty(exports, "DeliveryUnit", { enumerable: true, get: function () { return DeliveryUnitTypeGroup_1.DeliveryUnit; } });
Object.defineProperty(exports, "MaximumDeliveryUnit", { enumerable: true, get: function () { return DeliveryUnitTypeGroup_1.MaximumDeliveryUnit; } });
Object.defineProperty(exports, "MinimumDeliveryUnit", { enumerable: true, get: function () { return DeliveryUnitTypeGroup_1.MinimumDeliveryUnit; } });
const ShipmentTypeGroup_1 = require("./ShipmentTypeGroup");
Object.defineProperty(exports, "ShipmentType", { enumerable: true, get: function () { return ShipmentTypeGroup_1.ShipmentType; } });
const DeliveryTypeGroup_1 = require("./DeliveryTypeGroup");
Object.defineProperty(exports, "Delivery", { enumerable: true, get: function () { return DeliveryTypeGroup_1.Delivery; } });
const DeliveryTerms_1 = require("./DeliveryTerms");
Object.defineProperty(exports, "DeliveryTerms", { enumerable: true, get: function () { return DeliveryTerms_1.DeliveryTerms; } });
const PaymentMeans_1 = require("./PaymentMeans");
Object.defineProperty(exports, "PaymentMeans", { enumerable: true, get: function () { return PaymentMeans_1.PaymentMeans; } });
const PaymentTermsTypeGroup_1 = require("./PaymentTermsTypeGroup");
Object.defineProperty(exports, "PaymentTerms", { enumerable: true, get: function () { return PaymentTermsTypeGroup_1.PaymentTerms; } });
const PaymentTypeGroup_1 = require("./PaymentTypeGroup");
Object.defineProperty(exports, "PaymentType", { enumerable: true, get: function () { return PaymentTypeGroup_1.PaymentType; } });
Object.defineProperty(exports, "PrepaidPayment", { enumerable: true, get: function () { return PaymentTypeGroup_1.PrepaidPayment; } });
const ExchangeRateTypeGroup_1 = require("./ExchangeRateTypeGroup");
Object.defineProperty(exports, "ExchangeRate", { enumerable: true, get: function () { return ExchangeRateTypeGroup_1.ExchangeRate; } });
Object.defineProperty(exports, "PaymentExchangeRate", { enumerable: true, get: function () { return ExchangeRateTypeGroup_1.PaymentExchangeRate; } });
Object.defineProperty(exports, "PricingExchangeRate", { enumerable: true, get: function () { return ExchangeRateTypeGroup_1.PricingExchangeRate; } });
const TaxTotalTypeGroup_1 = require("./TaxTotalTypeGroup");
Object.defineProperty(exports, "TaxTotal", { enumerable: true, get: function () { return TaxTotalTypeGroup_1.TaxTotal; } });
Object.defineProperty(exports, "WithholdingTaxTotal", { enumerable: true, get: function () { return TaxTotalTypeGroup_1.WithholdingTaxTotal; } });
const TaxCategoryTypeGroup_1 = require("./TaxCategoryTypeGroup");
Object.defineProperty(exports, "TaxCategory", { enumerable: true, get: function () { return TaxCategoryTypeGroup_1.TaxCategory; } });
Object.defineProperty(exports, "ClassifiedTaxCategory", { enumerable: true, get: function () { return TaxCategoryTypeGroup_1.ClassifiedTaxCategory; } });
const TaxSubtotal_1 = require("./TaxSubtotal");
Object.defineProperty(exports, "TaxSubtotal", { enumerable: true, get: function () { return TaxSubtotal_1.TaxSubtotal; } });
const MonetaryTotalTypeGroup_1 = require("./MonetaryTotalTypeGroup");
Object.defineProperty(exports, "MonetaryTotal", { enumerable: true, get: function () { return MonetaryTotalTypeGroup_1.MonetaryTotal; } });
Object.defineProperty(exports, "LegalMonetaryTotal", { enumerable: true, get: function () { return MonetaryTotalTypeGroup_1.LegalMonetaryTotal; } });
const OrderLineReference_1 = require("./OrderLineReference");
Object.defineProperty(exports, "OrderLineReference", { enumerable: true, get: function () { return OrderLineReference_1.OrderLineReference; } });
const LineReferenceTypeGroup_1 = require("./LineReferenceTypeGroup");
Object.defineProperty(exports, "LineReference", { enumerable: true, get: function () { return LineReferenceTypeGroup_1.LineReference; } });
Object.defineProperty(exports, "DespatchLineReference", { enumerable: true, get: function () { return LineReferenceTypeGroup_1.DespatchLineReference; } });
Object.defineProperty(exports, "CallForTendersLineReference", { enumerable: true, get: function () { return LineReferenceTypeGroup_1.CallForTendersLineReference; } });
Object.defineProperty(exports, "CatalogueLineReference", { enumerable: true, get: function () { return LineReferenceTypeGroup_1.CatalogueLineReference; } });
Object.defineProperty(exports, "DependentLineReference", { enumerable: true, get: function () { return LineReferenceTypeGroup_1.DependentLineReference; } });
Object.defineProperty(exports, "ParentDocumentLineReference", { enumerable: true, get: function () { return LineReferenceTypeGroup_1.ParentDocumentLineReference; } });
Object.defineProperty(exports, "QuotationLineReference", { enumerable: true, get: function () { return LineReferenceTypeGroup_1.QuotationLineReference; } });
Object.defineProperty(exports, "ReceiptLineReference", { enumerable: true, get: function () { return LineReferenceTypeGroup_1.ReceiptLineReference; } });
Object.defineProperty(exports, "RequestLineReference", { enumerable: true, get: function () { return LineReferenceTypeGroup_1.RequestLineReference; } });
const PriceListTypeGroup_1 = require("./PriceListTypeGroup");
Object.defineProperty(exports, "PriceList", { enumerable: true, get: function () { return PriceListTypeGroup_1.PriceList; } });
const ItemTypeGroup_1 = require("./ItemTypeGroup");
Object.defineProperty(exports, "Item", { enumerable: true, get: function () { return ItemTypeGroup_1.Item; } });
Object.defineProperty(exports, "SupplyItem", { enumerable: true, get: function () { return ItemTypeGroup_1.SupplyItem; } });
const AllowanceChargeTypeGroup_1 = require("./AllowanceChargeTypeGroup");
Object.defineProperty(exports, "AllowanceCharge", { enumerable: true, get: function () { return AllowanceChargeTypeGroup_1.AllowanceCharge; } });
const PriceTypeGroup_1 = require("./PriceTypeGroup");
Object.defineProperty(exports, "Price", { enumerable: true, get: function () { return PriceTypeGroup_1.Price; } });
const ItemPriceExtensionTypeGroup_1 = require("./ItemPriceExtensionTypeGroup");
Object.defineProperty(exports, "ItemPriceExtension", { enumerable: true, get: function () { return ItemPriceExtensionTypeGroup_1.ItemPriceExtension; } });
const InvoiceLineTypeGroup_1 = require("./InvoiceLineTypeGroup");
Object.defineProperty(exports, "InvoiceLine", { enumerable: true, get: function () { return InvoiceLineTypeGroup_1.InvoiceLine; } });
const CreditNoteLineTypeGroup_1 = require("./CreditNoteLineTypeGroup");
Object.defineProperty(exports, "CreditNoteLine", { enumerable: true, get: function () { return CreditNoteLineTypeGroup_1.CreditNoteLine; } });
Object.defineProperty(exports, "SubCreditNoteLine", { enumerable: true, get: function () { return CreditNoteLineTypeGroup_1.SubCreditNoteLine; } });
const DebitNoteLineTypeGroup_1 = require("./DebitNoteLineTypeGroup");
Object.defineProperty(exports, "DebitNoteLine", { enumerable: true, get: function () { return DebitNoteLineTypeGroup_1.DebitNoteLine; } });
